const GET_COMMENTS_SAGA = 'app/comments/GET_COMMENTS_SAGA'
const GET_MORE_COMMENTS_SAGA = 'app/comments/GET_MORE_COMMENTS_SAGA'
const SET_COMMENTS = 'app/comments/SET_COMMENTS'
const SET_COMMENTS_LOADING = 'app/comments/SET_COMMENTS_LOADING'
const SET_MORE_COMMENTS = 'app/comments/SET_MORE_COMMENTS'
const ADD_COMMENT_SAGA = 'app/comments/ADD_COMMENT_SAGA'
const ADD_COMMENT_BEGIN = 'app/comments/ADD_COMMENT_BEGIN'
const ADD_COMMENT_SUCCESS = 'app/comments/ADD_COMMENT_SUCCESS'
const SET_COMMENTS_PAGINATING = 'app/comments/SET_COMMENTS_PAGINATING'
const DISABLE_PAGINATION = 'app/comments/DISABLE_PAGINATION'
const UNDO_LAST_COMMENT_ADD = 'app/comments/UNDO_LAST_COMMENT_ADD'

export {
  GET_COMMENTS_SAGA,
  SET_COMMENTS,
  SET_COMMENTS_LOADING,
  SET_MORE_COMMENTS,
  ADD_COMMENT_BEGIN,
  ADD_COMMENT_SUCCESS,
  GET_MORE_COMMENTS_SAGA,
  SET_COMMENTS_PAGINATING,
  ADD_COMMENT_SAGA,
  DISABLE_PAGINATION,
  UNDO_LAST_COMMENT_ADD
};
