const GET_FEED_SAGA = 'app/feed/GET_FEED_SAGA';
const SET_FEED = 'app/feed/SET_FEED'
const SET_FETCHING = 'app/feed/SET_FETCHING'
const TOGGLE_POST_LIKE_SAGA = 'app/feed/TOGGLE_POST_LIKE_SAGA' 
const UPDATE_LIKES = 'app/feed/UPDATE_LIKES'
const GET_LIKES_SAGA = 'app/feed/GET_LIKES_SAGA'
const DISABLE_LIKES_PAGINATION = 'app/feed/DISABLE_LIKES_PAGINATION'
const SET_LIKES_LOADING = 'app/feed/SET_LIKES_LOADING'
const SET_LIKES = 'app/feed/SET_LIKES'
const SET_LIKES_PAGINATING = 'app/feed/SET_LIKES_PAGINATING'
const INCREMENT_COMMENTS = 'app/feed/INCREMENT_COMMENTS'
const CLEAR_FEED = 'app/feed/CLEAR_FEED'
const ADD_LIKE = 'app/feed/ADD_LIKE'
const REMOVE_LIKE = 'app/feed/REMOVE_LIKE'

export {
  GET_FEED_SAGA,
  SET_FEED,
  SET_FETCHING,
  TOGGLE_POST_LIKE_SAGA,
  UPDATE_LIKES,
  GET_LIKES_SAGA,
  DISABLE_LIKES_PAGINATION,
  SET_LIKES_LOADING,
  SET_LIKES,
  SET_LIKES_PAGINATING,
  INCREMENT_COMMENTS,
  CLEAR_FEED,
  ADD_LIKE,
  REMOVE_LIKE
};
